version: '3'
services:
  spring_essentials:
    build:
      context: "./"
      dockerfile: "Dockerfile"
    image: spring_assignment
    ports:
      - '8080:8080'
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/spring_assignment_db?autoReconnect=true&useSSL=false
    depends_on:
      - db
  db:
    image: mysql:5.6
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=spring_assignment_db
      - MYSQL_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./docker/volume_mysql:/var/lib/mysql